---
- name: Install Lighthouse
  block:
    - name: Clone lighthouse repo
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        dest: /usr/share/nginx/www
        version: d701335

    - name: Add nginx config
      become: true
      ansible.builtin.template:
        src: templates/nginx.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: "0755"
      notify: Start nginx service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
